title: Jacob Ohlhausen
email: jaohlhausen@gmail.com
description: Jacob Ohlhausen specializes in engineering software configuration and development.
url: http://jacobohlhausen.com

theme: jekyll-theme-cayman
timezone: America/Chicago
